env:
  - DB=postgres
  - DJ_DEBUG=False
  - DATABASE_URL=postgres://postgres@localhost/travisdb
language: python
python:
    - 3.9
services:
    - postgresql
before_install:
  - export DJ_DEBUG=False
  - export DATABASE_URL=postgres://postgres@localhost/travisdb
before_script:
    - psql -c "CREATE DATABASE travisdb;" -U postgres
    - python manage.py migrate --noinput
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: clickoh
    run: python manage.py migrate
    on: master
